# Generated by Django 4.2.30 on 2026-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_video',
            field=models.BooleanField(default=True, help_text='Show video on detail page'),
        ),
    ]
