# Generated by Django 4.2.30 on 2026-06-10 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0003_post_show_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post_created', 'সংবাদ তৈরি'), ('post_deleted', 'সংবাদ মুছে ফেলা'), ('post_updated', 'সংবাদ সম্পাদনা'), ('moderator_added', 'মডারেটর যোগ'), ('moderator_removed', 'মডারেটর অপসারণ'), ('login', 'লগইন')], max_length=30)),
                ('target_label', models.CharField(blank=True, default='', help_text='E.g. post title or moderator username affected', max_length=300)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
