# Generated by Django 4.2.30 on 2026-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_user_report',
            field=models.BooleanField(default=False, help_text='Mark as a raw user submission from the public report form'),
        ),
    ]
