# Generated by Django 4.2.30 on 2026-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_activitylog_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sensitive_image',
            field=models.BooleanField(default=False, help_text='Mark if the image contains sensitive content (blur effect)'),
        ),
    ]
