# Generated by Django 4.2.30 on 2026-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_post_is_sensitive_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated SEO-friendly URL segment. Format: {id}-{title}-{division}-{date}', max_length=300, unique=True),
        ),
    ]
