# Generated by Django 4.2.30 on 2026-06-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='অবিস্মরণীয় জুলাই', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Toggle to activate this campaign on the frontend.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='e.g. 15 for 15th day')),
                ('date', models.DateField(db_index=True)),
                ('video_url', models.URLField(blank=True, default='', help_text='YouTube or Facebook video link (optional)')),
                ('image', models.ImageField(blank=True, help_text='Optional image if video is not available', null=True, upload_to='campaigns/')),
                ('summary_text', models.TextField(blank=True, default='', help_text='Narrative for this day')),
                ('read_more_link', models.URLField(blank=True, default='', help_text="Link to read today's analysis")),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='archive.campaign')),
            ],
            options={
                'ordering': ['date', 'day_number'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
