# Generated by Django 4.2.30 on 2026-06-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_campaign_campaignday'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
