# Generated by Django 4.2.30 on 2026-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='অপরাধনামা ডেক্স', help_text='Author or reporter name for Google News transparency', max_length=100),
        ),
    ]
