# Generated by Django 4.2.30 on 2026-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_slug',
            field=models.CharField(blank=True, help_text='Custom URL slug segment (optional). If provided, it overrides the auto-generated title slug.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Optional SEO keywords to push/append into the URL slug (comma-separated).', max_length=300, null=True),
        ),
    ]
